### ISSUE TITLE
tensor size mismatch

### ISSUE THREAD

**Issue by EricStarer** [KumapowerLIU/Rethinking-Inpainting-MEDFE#30]
Here is the error message, could anyone give me some help?
`Traceback (most recent call last):
  File "train.py", line 33, in <module>
    model.optimize_parameters()
  File "/DeepLearning/xing_zhao/inpainting/Rethinking-Inpainting-MEDFE/models/MEDFE.py", line 190, in optimize_parameters
    self.forward()
  File "/DeepLearning/xing_zhao/inpainting/Rethinking-Inpainting-MEDFE/models/MEDFE.py", line 138, in forward
    x_out = self.netMEDFE(De_in, self.mask_global)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/DeepLearning/xing_zhao/inpainting/Rethinking-Inpainting-MEDFE/models/networks.py", line 112, in forward
    out = self.pc_block(input, mask)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/DeepLearning/xing_zhao/inpainting/Rethinking-Inpainting-MEDFE/models/PCconv.py", line 337, in forward
    x_ST_3 = self.cov_3(x_ST)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/DeepLearning/xing_zhao/inpainting/Rethinking-Inpainting-MEDFE/models/PCconv.py", line 84, in forward
    out = self.conv(out)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/DeepLearning/xing_zhao/inpainting/Rethinking-Inpainting-MEDFE/models/PCconv.py", line 247, in forward
    output = self.input_conv(input * mask)
RuntimeError: The size of tensor a (32) must match the size of tensor b (37) at non-singleton dimension 3
`

**Comment by EricStarer** [comment]
my batchsize is 1 and finesize is 256
